context.objects = [
  { factory = adapter
    args = {
      factory.name     = support.null-audio-sink
      node.name        = "scarlet-input"
      node.description = "Scarlett 4i4 Input"
      media.class      = Audio/Source/Virtual
      audio.position   = [ MONO ]
    }
  }
]
