context.modules = [
  { name = libpipewire-module-loopback
    args = {
      capture.props = {
        node.name        = "obs-audio-input"
        node.description = "OBS Audio Input"
        media.class      = Audio/Sink
        audio.position   = [ FL FR ]
      }
      playback.props = {
        node.name           = "obs-audio-input.output"
        audio.position      = [ FL FR ]
        target.object       = "alsa_output.usb-Focusrite_Scarlett_4i4_4th_Gen_S43Y1M05C0E5D8-00.analog-surround-21"
        node.passive        = true
        node.dont-reconnect = true
      }
    }
  }
]
