-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

hl.config({
	input = {
		kb_layout = "",  -- empty inherits XKB_DEFAULT_LAYOUT (libxkbcommon), falls back to "us"
        repeat_rate = 30,
        repeat_delay = 250,
        sensitivity = 0,
        accel_profile = "flat",
        force_no_accel = 1,
        follow_mouse = 1,
		numlock_by_default = true,
		touchpad = {
			tap_to_click = true,
			natural_scroll = false,
		},
	},
	general = {
		gaps_in = 4,
		gaps_out = 8,
		border_size = 1,
		layout = "dwindle",
	},
	decoration = {
		rounding = 8,
        rounding_power = 2,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696
        }
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
    ecosystem = {
        no_update_news = true,
        no_donation_nag = true
    },
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
    animations = {
        enabled = false
    }
})

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.window_rule({
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},
	no_focus = true,
})
hl.workspace_rule({ workspace = "1", monitor = "DP-1" })
hl.workspace_rule({ workspace = "2", monitor = "DP-1" })
hl.workspace_rule({ workspace = "3", monitor = "DP-3" })
hl.workspace_rule({ workspace = "4", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "5", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "6", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "name:music", monitor = "DP-3" })

hl.window_rule({ match = { class = "^steam_app_\\d+$" }, workspace = "2", fullscreen = true })
hl.window_rule({ match = { class = "^([Gg]imp)" }, workspace = "2" })
hl.window_rule({ match = { class = "^(waywall|Minecraft)" }, workspace = "2" })
hl.window_rule({ match = { class = "^(firefox)$" }, workspace = "3" })
hl.window_rule({ match = { class = "^(com\\.obsproject\\.Studio)$" }, workspace = "4" })
hl.window_rule({ match = { class = "^(discord)$" }, workspace = "5" })
hl.window_rule({ match = { class = "^(steam)$" }, workspace = "6" })
hl.window_rule({ match = { class = "^[Ss]potify$" }, workspace = "name:music" })

hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")
require("env")
