-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "3840x0", scale = 1 })
-- hl.monitor({ output = "DP-1", mode = "3840x2160@143.999", position = "1920x0", scale = 1.5, vrr = 0 })
hl.monitor({ output = "DP-1", mode = "2560x1440@143.999", position = "1920x0", scale = 1, vrr = 0 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@59.939", position = "4480x0", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-3", mode = "1920x1080@143.855", position = "0x0", scale = 1, vrr = 0 })
