[tools]
age = "latest"
aube = "latest"
bat = "latest"
claude = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
gh = "latest"
"github:afrigon/clock" = "latest"
"github:afrigon/mc" = { version = "latest", minimum_release_age = "0" }
"github:afrigon/snorm" = "latest"
herdr = "latest"
jq = "latest"
just = "latest"
python = "3.14"
ripgrep = "latest"
starship = "latest"
tree-sitter = "latest"
usage = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }

[settings]
python.default_packages_file = "~/.config/mise/default-python-packages"
